### ISSUE TITLE
SQL文件中存在错误

### ISSUE THREAD

**Issue by jackytsu** [xxjwxc/shares#8]
1、建表SQL文件中缺少good_shares_tbl、analy_tdx_after_tbl、analy_tdx_tbl这三张表的相关SQL；
2、视图SQL文件中第72行（ma20_view）的创建语句中指定的schema错误，可以去掉。

**Comment by xxjwxc** [comment]
不影响这个

**Comment by iszmxw** [comment]
> 不影响这个

是啊一点也不影响
